# Generated by Django 6.0.1 on 2026-04-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pharmacybill_billitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacybill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
