# Generated by Django 6.0.1 on 2026-04-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_pharmacybill_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Ointment/Cream', 'Ointment/Cream'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler'), ('General/Consumable', 'General/Consumable')], default='General/Consumable', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='rack_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
