# Generated by Django 6.0.1 on 2026-01-20 08:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'hospital_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('doctor_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('qualifications', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('work_days', models.CharField(max_length=50)),
                ('shift_type', models.CharField(max_length=20)),
                ('slot_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ('max_patients', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='hospital.department')),
            ],
            options={
                'db_table': 'hospital_doctor',
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nurse_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('qualifications', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('work_days', models.CharField(max_length=50)),
                ('shift_type', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nurses', to='hospital.department')),
            ],
            options={
                'db_table': 'hospital_nurse',
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('assigned_slot', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospital_patient',
                'ordering': ['patient_id'],
                'indexes': [models.Index(fields=['patient_name'], name='hospital_pa_patient_37dd07_idx'), models.Index(fields=['created_at'], name='hospital_pa_created_c45760_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('Normal', 'Normal'), ('Emergency', 'Emergency'), ('Critical', 'Critical')], default='Normal', max_length=20)),
                ('visit_date', models.DateField()),
                ('medicines', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('slot', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='hospital.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hospital.patient')),
            ],
            options={
                'db_table': 'hospital_visit',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['department'], name='hospital_do_departm_80c757_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['doctor_name'], name='hospital_do_doctor__6778b8_idx'),
        ),
        migrations.AddIndex(
            model_name='nurse',
            index=models.Index(fields=['department'], name='hospital_nu_departm_80214d_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', 'visit_date'], name='hospital_vi_patient_3fe133_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['doctor', 'visit_date'], name='hospital_vi_doctor__03af08_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['department', 'visit_date'], name='hospital_vi_departm_c90eae_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['case_type'], name='hospital_vi_case_ty_aaf989_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['-visit_date'], name='hospital_vi_visit_d_c444b3_idx'),
        ),
    ]
