# Generated by Django 6.0.1 on 2026-03-09 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('Lab Report', 'Lab Report'), ('Prescription', 'Prescription'), ('Scan', 'Scan/X-Ray/MRI'), ('Discharge Summary', 'Discharge Summary'), ('Other', 'Other')], default='Other', max_length=50)),
                ('file', models.FileField(upload_to='patient_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hospital.patient')),
            ],
            options={
                'db_table': 'hospital_patientdocument',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['patient'], name='hospital_pa_patient_dc1af3_idx'), models.Index(fields=['document_type'], name='hospital_pa_documen_f7736a_idx')],
            },
        ),
    ]
