# Generated by Django 6.0.1 on 2026-04-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='PREDICTCARE', max_length=255)),
                ('hospital_subtitle', models.CharField(default='Pharmacy & Wellness Center', max_length=255)),
                ('hospital_address', models.TextField(default='123 Healthcare Avenue, Medical District')),
                ('hospital_phone', models.CharField(default='+1 (555) 900-HOSP', max_length=50)),
                ('hospital_email', models.EmailField(default='pharmacy@bmh-hospital.com', max_length=254)),
                ('hospital_footer_text', models.TextField(default='Thank you for choosing PredictCare (BMH Hospital Pharmacy).')),
            ],
            options={
                'verbose_name': 'Hospital Configuration',
                'verbose_name_plural': 'Hospital Configuration',
                'db_table': 'hospital_configuration',
            },
        ),
    ]
